### ISSUE TITLE
Wrong spot

### ISSUE THREAD

**Issue by Sushi-Mampfer** [jamisonderek/flipper-zero-tutorials#11]
I am using a iPhone se 3th gen, and it clicks somewhere below and to the left of the cookie.

**Comment by jamisonderek** [comment]
You are the second person to say that clicking needs to be somewhere else.  I will use this issue to add a feature request for:
- config setting to allow setting the X and Y location of the click.
- config setting to set the delays in setting the location.

**Comment by ZekePolarisBSH** [comment]
I guess that makes me third the nerd. Can't wait

**Comment by jamisonderek** [comment]
I updated the clicker so now there is a configuration for offset X, offset Y and a repeat count.  I used Whiteboard app to see where it was clicking and picked defaults of (x:30,y:80) repeat: 3.  

NOTE: I think the 50ms repeat is fine, so I decided to not make that configurable.

**Comment by jamisonderek** [comment]
I ended up adding configurable delay as well.  Samsung phones need much bigger values than iPhones.  Updated the bottom of Instructions tab with some examples.
