### ISSUE TITLE
Hint for Wiki : add info for autogenerated .h regarding the icons

### ISSUE THREAD

**Issue by ziolelle** [jamisonderek/flipper-zero-tutorials#12]
Hi, again I want to thank you for your work.

Just a hint: 

In the Wiki:
https://github.com/jamisonderek/flipper-zero-tutorials/wiki/User-Interface#draw-icon
Would you mind to add a little explanation about the need to include the "auto-generated" file .h by ./fbt for the Icon identifiers?
Probably I missed it...

**Comment by jamisonderek** [comment]
Thanks for the feedback.  I'll try to add it soon.

**Comment by jamisonderek** [comment]
Sorry it took so long to update.  Thanks again for the feedback.
