### ISSUE TITLE
TextBox module documentation

### ISSUE THREAD

**Issue by br0ziliy** [jamisonderek/flipper-zero-tutorials#15]
I've no idea how to create an MR for a Wiki, but here's the diff and pictures for the TextBox GUI module.
[0001-Document-TextBox-GUI-module.patch](https://github.com/jamisonderek/flipper-zero-tutorials/files/12344374/0001-Document-TextBox-GUI-module.patch)
![text-box-font-text](https://github.com/jamisonderek/flipper-zero-tutorials/assets/1941223/3cb6843d-67f7-4fa5-80e3-babe79ca6aeb)
![text-box-font-hex](https://github.com/jamisonderek/flipper-zero-tutorials/assets/1941223/1c53b53c-bc3c-4468-970f-19ec3dbb3b89)
![text-box](https://github.com/jamisonderek/flipper-zero-tutorials/assets/1941223/56c4a77f-a2e0-4628-b670-b63061438b40)

**Comment by jamisonderek** [comment]
Thanks for the contribution.  I merged it into the official wiki!

**Comment by jamisonderek** [comment]
I also added you to https://github.com/jamisonderek/flipper-zero-tutorials/wiki#contributors   Let me know if you prefer a different display name be shown.
