### ISSUE TITLE
Unable to compile rolling codes app

### ISSUE THREAD

**Issue by celowsky** [jamisonderek/flipper-zero-tutorials#16]
When I try to follow methods 3 and 4 mentioned in this [document]([flipper-zero-tutorials](https://github.com/jamisonderek/flipper-zero-tutorials/blob/7595c42fdccc9f040dc399790d679b7784e2811b/subghz/apps/rolling-flaws/README.md?plain=1#L238) I receive the following error:
```
flipper-zero-tutorials\subghz\apps\rolling-flaws\rolling_flaws_subghz_receive.h:7:10: fatal error: lib/subghz/protocols/protocol_items.h: No such file or directory
    7 | #include <lib/subghz/protocols/protocol_items.h>
```

I'm unclear on what I'm missing

**Comment by jamisonderek** [comment]
Thanks for the bug report.  It appears building under ufbt is not supported and not something I'll be able to fix.

I updated the steps for VSCode, so hopefully it's more clear now.  If not, please let me know here or on my Discord server -
https://discord.com/invite/NsjCvqwPAd
