### ISSUE TITLE
Build error on Flipc.org

### ISSUE THREAD

**Issue by chryss44** [jamisonderek/flipper-zero-tutorials#19]
Build error on flipc.org for Xtreme, can you look at the problem, perhaps it's normal ?
<img width="745" alt="Capture d’écran 2023-12-09 à 12 42 08" src="https://github.com/jamisonderek/flipper-zero-tutorials/assets/32177747/9bc5550a-b123-4657-a5cb-7494a56e71a0">

**Comment by jamisonderek** [comment]
Problem solved... no more Flipc.org. :(
