### ISSUE TITLE
GPIO_BLINK: Discrepancy between README pinout and GPIO initialization mode

### ISSUE THREAD

**Issue by llgarrido** [jamisonderek/flipper-zero-tutorials#27]
Hello,

I was running the code i noticed that the LED is initialized in `GpioModeOutputOpenDrain` mode:

```c
furi_hal_gpio_init_simple(pin_led, GpioModeOutputOpenDrain);
```

However, the README suggests connecting the LED between the GPIO pin and GND. This setup would work if the GPIO pin was initialized in `GpioModeOutputPushPull` mode instead of `GpioModeOutputOpenDrain`.

Am I wrong?

I suggest changing the GPIO initialization mode to `GpioModeOutputPushPull` if the intention is to connect the LED between the GPIO pin and GND.

Thank you for your attention to this matter.

**Comment by jamisonderek** [comment]
You are correct, thank you so much for reporting the issue.  I'm surprised that you are the first person to report the issue.  I updated the documentation and code to reflect PushPull when the other pin is connected to GND.
