### ISSUE TITLE
New Serial Api

### ISSUE THREAD

**Issue by benjamindrussell** [jamisonderek/flipper-zero-tutorials#29]
The Flipper Zero serial API has been updated in the latest release, and it doesn't seem to be backwards compatible with the old API. FuriHalUartID and UartIrqEvent no longer exist.

**Comment by jamisonderek** [comment]
I need to test the firmwares to see who is still on the old firmware.

I need to update gpio\uart_demo to use the uart_helper-new and maybe a #define to switch between the implementations if there are old firmware out there still.

**Comment by jamisonderek** [comment]
Updated https://github.com/jamisonderek/flipper-zero-tutorials/commit/94c5e6587caa6dc1d02198eb805690a352aecdec for the new API.

Also, I added ability to read the current text without having to have a delimiter, since sometimes that is what is required by a few apps.
