### ISSUE TITLE
Update the Rock Paper Scissors app for the SDK version 0.85 f7

### ISSUE THREAD

**Issue by furippa** [jamisonderek/flipper-zero-tutorials#30]
Hello!

Your Rock Paper Scissors app version `1.3` fails to build with the SDK version `0.85.2-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64afb8af44f416a1559b8250/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/6483518399)

Flipper Team

**Comment by jamisonderek** [comment]
version 1.5 of rock_paper_scissors works with latest API.
