### ISSUE TITLE
wiegand app cannot compile

### ISSUE THREAD

**Issue by CountParadox** [jamisonderek/flipper-zero-tutorials#35]
Hi @jamisonderek 

No matter what I do, I cannot get the wiegand app to compile.
I was getting a number of errors relating to furi declerations, and after potentially solving those I am now getting errors regarding members and years, months, etc.

I am well out of my depth here and would really appreciate some assistance in getting this working! 

I want to test some wiegand readers with my flipper, and have plans to design a wiegand interface PCB for them if i can get your app working.

**Comment by CountParadox** [comment]
I found a compiled version elsewhere that works. 
Also, can the app turn on 5v by default ?

**Comment by kcrad100** [comment]
@CountParadox, could you possibly share the link to the compiled version?

**Comment by jamisonderek** [comment]
I'll take a look tomorrow. Which firmware are you running?

**Comment by jamisonderek** [comment]
Fixed https://github.com/jamisonderek/flipper-zero-tutorials/commit/e6debaf3884a339044ca84d703c4702a4c671157
