### ISSUE TITLE
App not downloading via flipper lab

### ISSUE THREAD

**Issue by gameking2011** [jamisonderek/flipper-zero-tutorials#38]
every time I try to install the fmf_to_sub-ghz app it says:
Error: Failed to fetch application build (1008)
please fix the error

**Comment by gameking2011** [comment]
there is no .fap file

**Comment by jamisonderek** [comment]
I'm not seeing any error.  What firmware are you on?

Step 1. https://lab.flipper.net/apps/fmf_to_sub
Step 2. Click "Install" button
Step 3. On Flipper open "Apps / Sub-GHz/ Music to Sub-GHz Radio"
Application loads without any error - shows "Configure / Convert / About" screen.
