### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by JackalopeHunter26** [jamisonderek/flipper-zero-tutorials#39]
Whenever I launch the app it crashes. I get a “furi_check failed” error

**Comment by jamisonderek** [comment]
Which app are you trying to run and which firmware version do you have installed on the Flipper?

**Comment by JackalopeHunter26** [comment]
Genie Door Recorder, firmware version momentum MNTN-005Sent from my iPhoneOn Sep 3, 2024, at 8:14 PM, Derek Jamison ***@***.***> wrote:﻿
Which app are you trying to run and which firmware version do you have installed on the Flipper?

**Comment by jamisonderek** [comment]
[genie_record.zip](https://github.com/user-attachments/files/17452572/genie_record.zip)

Genie v3.0 works with latest dev build of momentum without any furi_check getting triggered.

**Comment by jamisonderek** [comment]
You can also install from
https://lab.flipper.net/apps/genie_record now.
