### ISSUE TITLE
Wrong pins for I2C

### ISSUE THREAD

**Issue by mpmarks** [jamisonderek/flipper-zero-tutorials#4]
The project readme docs here say SCL goes to Flipper pin 15   SDA to  pin 16. Looking at the flipper docs that it reversed.
 I tried a BLE280 sensor and found SCL ->16, SDA -> 15 works.

**Comment by jamisonderek** [comment]
Thanks for reporting this issue!  I had the screen output correct with "pin15=SDA. pin16=SCL", but the readme and top comments were both wrong.  😿
